podlove/radiator

assets/package-lock.json
assets/package.json

Updates the node dependencies, so there are no active vulns according to `npm audit`:
```
$ npm audit
=== npm audit security report ===                        
found 0 vulnerabilities
in 8776 scanned packages
```
This is the fix for #18.

Add: Fix node vulns

---

README.md
lib/radiator/auth/guardian.ex
lib/radiator_web/plug/validate_api_user.ex
lib/radiator_web/resolvers/editor.ex
lib/radiator_web/resolvers/session.ex
lib/radiator_web/router.ex
lib/radiator_web/schema.ex
lib/radiator_web/schema/middleware/require_authentication.ex
lib/radiator_web/schema/middleware/translate_changeset.ex
lib/radiator_web/schema/user_types.ex
test/radiator_web/schema/mutation/networks_test.exs
test/radiator_web/schema/mutation/users_test.exs
test/support/test_entries.ex

* the `authenticatedSession` mutation now returns a `session` object with a token that needs to be put into the `Authorization:` header with a `Bearer ` prefix to have authenticated api calls.
* put Authentication in place for the `createNetwork` mutation. Default TTL is 45 minutes.
* add a `prolongSession` mutation to get a new token with full TTL to not need credentials again in a potential frontend app that is in use. 
* update `network_tests` to use this. 
* add `users_tests` for session related tests
* move middleware to `Radiator.Schema.Middleware`, rename `ChangesetMiddleware` to `Middleware.TranslateChangeset`
Fixes #45 
Fixes #46

feat(api,auth,perm): add api to generate access token with credentials, use these credentials in an api call

---

config/test.exs

should close #51 
> The following values can be used to speed up tests.
>
> ```elixir
>config :argon2_elixir,
>  t_cost: 1,
>  m_cost: 8
> ```
from [argon2_elixir docs](https://hexdocs.pm/argon2_elixir/Argon2.Stats.html#module-test-values)

chore(argon2_elixir): speed up password hashing during test

---

.drone.yml
.travis.yml
README.md
config/config.exs
config/test.exs
notes.md

Reason: We now need minio to run for tests, which was a headscratcher with Travis but straightforward with Drone CI, suggested by @alexander-heimbuch 
https://cloud.drone.io/podlove/radiator

Replace Travis CI with Drone CI

---

lib/radiator_web/channels/user_socket.ex
lib/radiator_web/graphql/resolvers/directory.ex
lib/radiator_web/graphql/resolvers/editor.ex
lib/radiator_web/graphql/resolvers/session.ex
lib/radiator_web/graphql/resolvers/storage.ex
lib/radiator_web/graphql/schema.ex
lib/radiator_web/graphql/schema/directory_types.ex
lib/radiator_web/graphql/schema/episode_types.ex
lib/radiator_web/graphql/schema/media_types.ex
lib/radiator_web/graphql/schema/middleware/require_authentication.ex
lib/radiator_web/graphql/schema/middleware/translate_changeset.ex
lib/radiator_web/graphql/schema/storage_types.ex
lib/radiator_web/graphql/schema/user_types.ex
lib/radiator_web/router.ex
test/radiator_web/graphql/schema/mutation/episodes_test.exs
test/radiator_web/graphql/schema/mutation/networks_test.exs
test/radiator_web/graphql/schema/mutation/podcasts_test.exs
test/radiator_web/graphql/schema/mutation/upload_test.exs
test/radiator_web/graphql/schema/mutation/users_test.exs
test/radiator_web/graphql/schema/query/episodes_test.exs
test/radiator_web/graphql/schema/query/networks_test.exs
test/radiator_web/graphql/schema/query/podcasts_test.exs

refactor: move all graphql modules into GraphQL namespace

---

config/dev.exs
lib/radiator/email/email_console_adapter.ex

This pr introduces a new Bamboo.Adapter which logs the emails to the console.
It also activates it for the dev profile.
The idea behind it is to be able to see the sent emails immediately in the console without having to configure an smtp server for development.
I'm absolutely new to Elixir and this tech stack. So if there are things completely wrong, please tell me.
I was not sure if i should use `IO.puts` to print to the console. But i didn't find other logging things in the project so i went with it.

Log emails to console in dev profile

---

lib/radiator/directory.ex
lib/radiator_web/graphql/resolvers/directory.ex
lib/radiator_web/graphql/schema/directory_types.ex
test/radiator/directory/directory_test.exs
test/radiator_web/graphql/schema/query/podcasts_test.exs

I'm not too happy with making an extra database query to get the `episode_count`. Open to suggestions for a better idea. 😋
---
closes #62, when merged

feat(api,graphql): add episodesCount to podcast GraphQL queries

---

lib/radiator/directory/episode.ex
lib/radiator_web/graphql/admin/resolvers/editor.ex
lib/radiator_web/graphql/public/resolvers/directory.ex
test/radiator_web/graphql/admin/schema/query/episodes_test.exs
test/radiator_web/graphql/public/schema/query/episodes_test.exs

fix: query enclosure of episode in gql

---

config/dev.exs
config/test.exs
lib/radiator/auth/guardian.ex
lib/radiator/directory/importer.ex
lib/radiator_web/controllers/login_controller.ex
lib/radiator_web/graphql/admin/resolvers/session.ex
lib/radiator_web/graphql/admin/resolvers/user.ex
lib/radiator_web/graphql/admin/schema/middleware/require_authentication.ex
lib/radiator_web/graphql/common/types.ex
lib/radiator_web/graphql/helpers/user_helpers.ex
lib/radiator_web/graphql/public/resolvers/session.ex
lib/radiator_web/graphql/public/resolvers/user.ex
lib/radiator_web/graphql/schema.ex
lib/radiator_web/plug/validate_api_user.ex
test/radiator_web/graphql/admin/schema/mutation/users_test.exs
test/support/factory.ex
test/support/test_entries.ex

feat(api): add expirydate to session result for `authenticatedSession` and `prolongSession`
fix(api): requiring active users now for admin api
fixes #75

feature(api): add `userSignup` to graphQL api

---

lib/radiator/directory/editor/manager.ex
lib/radiator/directory/episode.ex
lib/radiator/media/audio_file_upload.ex
lib/radiator_web/controllers/admin/episode_controller.ex
lib/radiator_web/templates/admin/episode/form.html.eex
lib/radiator_web/templates/admin/episode/show.html.eex

Add enough functionality to create usable episodes via Phoenix UI.
- reenable audio file upload
- publish episodes on creation (temporarily until there are publish buttons)
- fix mp3 upload mime type when necessary
- hide chapters if there are none
- support episode image in form
- move upload logic from controller to schema/changeset

Phoenix UI: improve episode form

---

guides/rest_api.md
lib/radiator_web.ex
lib/radiator_web/controllers/api/audio_controller.ex
lib/radiator_web/controllers/api/audio_file_controller.ex
lib/radiator_web/controllers/api/authentication_controller.ex
lib/radiator_web/controllers/api/collaborator_controller.ex
lib/radiator_web/controllers/api/episode_controller.ex
lib/radiator_web/controllers/api/file_controller.ex
lib/radiator_web/controllers/api/network_controller.ex
lib/radiator_web/controllers/api/podcast_controller.ex
lib/radiator_web/helpers/rest_api_helpers.ex

add: a line of documentation to clarify this
add: `RestApiHelper` for the consistent response send on delete
add: `rest_controller` as option for the use line to include all things necessary for rest controllers
fixes #150

fix(api): make REST delete always return 204 if authenticated and params are ok

---

lib/radiator/directory.ex
lib/radiator/directory/editor.ex
lib/radiator/directory/editor/manager.ex
lib/radiator_web/graphql/admin/resolvers/editor.ex
lib/radiator_web/graphql/admin/types.ex
lib/radiator_web/graphql/common/types.ex
lib/radiator_web/graphql/public/resolvers/directory.ex
lib/radiator_web/graphql/public/types.ex
lib/radiator_web/graphql/schema.ex
lib/radiator_web/views/api/podcast_view.ex
test/radiator_web/graphql/admin/schema/query/episodes_test.exs
test/radiator_web/graphql/public/schema/query/episodes_test.exs

- removes deprecated `enclosure` from API
- list audios for network
- list episodes for an audio
- list audio files for an audio
Not everything is implemented in public + cms API. For example I don't think it's necessary to access all network-audios publicly.
closes #158

GraphQL Audio Access

---

guides/data_and_structure.md
guides/graphql_api.md
guides/rest_api.md
lib/radiator/directory/episode.ex
lib/radiator/directory/importer.ex
lib/radiator/feed/episode_builder.ex
lib/radiator_web/controllers/player_controller.ex
lib/radiator_web/graphql/admin/types.ex
lib/radiator_web/graphql/public/types.ex
lib/radiator_web/templates/admin/episode/form.html.eex
lib/radiator_web/templates/admin/episode/show.html.eex
lib/radiator_web/templates/public/episode/_episode_entry.html.eex
lib/radiator_web/templates/public/episode/index.html.eex
lib/radiator_web/templates/public/episode/show.html.eex
lib/radiator_web/views/admin/episode_view.ex
lib/radiator_web/views/api/episode_view.ex
lib/radiator_web/views/api/podcast_view.ex
priv/repo/migrations/0400_create_episodes.exs
test/radiator/feed/builder_test.exs

* change episode fields `description`,`content` to `summary`,`summary_html` and `summary_source`
* updated admin, public interface and feed to reflect those
* update documentation too
* made rest api return image urls instead of image types
* made rest api capable of setting images and summary fields 
fixes #164 
needs ecto.reset

feature(content, api): align episode api with documentation, provide rest api for image and summary fields

---

guides/rest_api.md
lib/radiator/directory/audio_publication.ex
lib/radiator/directory/editor.ex
lib/radiator/directory/editor/manager.ex
lib/radiator_web/controllers/api/audio_controller.ex

Via discussion in Slack: make it easier for API consumer to create an audio with episode / audio publication by taking parameters for the episode / audio publication while creating the audio.
/cc @Fischaela

feat(rest-api): when creating audio, allow params for episode/audio publication

---

README.md
docker-compose.yml

mailhog is a replacement for mailtrap.io. All local, no accounts/internet required.
I don't think our radiator container should provide an smtp service. In production you probably want to use SES/SendGrid/MailGun/... or spin up an smtp container like https://hub.docker.com/r/namshi/smtp.

add: local email smtp container

---

lib/radiator/auth/register.ex
lib/radiator/auth/user.ex
lib/radiator/directory/editor.ex
lib/radiator/directory/user_profile.ex
lib/radiator/media/user_avatar.ex
lib/radiator_web/graphql/admin/resolvers/editor.ex
lib/radiator_web/graphql/admin/types.ex
lib/radiator_web/templates/layout/_nav.html.eex
lib/radiator_web/templates/shared_partials/_collaborator_list.html.eex
lib/radiator_web/views/helpers/content_helpers.ex
priv/repo/migrations/0500_add_users_table.exs
priv/repo/migrations/0550_add_user_profiles_table.exs
test/support/factory.ex

I detached People from Users. Instead, a UserProfile is now created together with each user.
UserProfile currently holds the `display_name` and `image`. `User` now only holds fields that are required for Auth stuff.
I wonder if we should expose this separation of User and Profile in the APIs at all? My gut says no, only expose a single "user" object in REST/gql as this separation is mainly an architecture choice to keep Auth.User clean.
I put UserProfile in `Radiator.Directory` because it is kind of public information? Otherwise we would probably a new context because neither does it fit into `Auth` nor `Contribution`.
⚠️ requires `mix ecto.reset`
issue #200

refactor architecture: User/Person/UserProfile

---

config/config.exs

There is an issue between hackney and OTP 22.1, see https://github.com/benoitc/hackney/pull/589
This is a workaround that explicitly unsets the problematic setting for ua_inspector (which uses hackney)

fix: ua_inspector crashing builds

---

lib/radiator/directory/episode.ex
lib/radiator/directory/podcast.ex
lib/radiator_web/graphql/admin/resolvers/editor.ex
lib/radiator_web/graphql/public/resolvers/directory.ex
test/radiator/directory/directory_test.exs

* also fixed that return value of `podcast(id:) {episodes}` query includes all episodes

fix(graphql-api): hardened queries with `publicPage` and `publishedFeeds` against missing data

---

guides/rest_api.md
lib/radiator_web/graphql/admin/resolvers/editor.ex
lib/radiator_web/graphql/admin/types.ex
test/radiator_web/graphql/admin/schema/query/episodes_test.exs
test/radiator_web/graphql/admin/schema/query/podcasts_test.exs

- gql: remove isPublished from episode and podcast
- gql: both episode and podcast now have a publishState accessor returning "drafted", "scheduled", "published" or "unpublished"
- REST: both episode and podcast now support the "publish_state" field on UPDATE/CREATE
fixes #237

cleanup publication state API

---

.drone.yml
config/releases.exs

Ensure ffmpeg is available in the test container.
Removes the explicit ffmpex config, which is not required.

chore: fix drone ci

---

Dockerfile

Forces us to deal with warnings right away and makes it immediately apparent when a dependency update introduces warnings.

chore: ensure docker image is free from elixir warnings

---

config/config.exs
lib/radiator/directory/editor.ex
lib/radiator/directory/editor/editor.ex
lib/radiator/directory/editor/manager.ex
lib/radiator/feed/builder.ex
lib/radiator/feed/generator.ex
lib/radiator/feed/podcast_builder.ex
lib/radiator/feed/storage.ex
lib/radiator/feed/worker.ex
lib/radiator/media/feed_file.ex
lib/radiator/storage/storage.ex
lib/radiator_web/controllers/public/feed_controller.ex
mix.exs
mix.lock
test/radiator_web/controllers/api/audio_file_controller_test.exs
test/radiator_web/controllers/feed_controller_test.exs

Instead of serving feeds on-demand, static feed files are generated every time podcast or episode data changes, and stored on disk. Public feed URLs are dynamic and incoming requests redirected to the static file, similar to how audio files are handled.
closes #259

feature: feeds as files

---

guides/rest_api.md
lib/radiator/directory/audio_publication.ex
lib/radiator/directory/editor.ex
lib/radiator/directory/editor/manager.ex
lib/radiator/directory/episode.ex
lib/radiator/directory/podcast.ex
lib/radiator_web/controllers/api/audio_publication_controller.ex
lib/radiator_web/controllers/api/episode_controller.ex
lib/radiator_web/controllers/api/podcast_controller.ex
lib/radiator_web/helpers/rest_api_helpers.ex
lib/radiator_web/router.ex
test/radiator/directory/directory_test.exs
test/radiator/directory/title_slug_test.exs
test/radiator_web/controllers/api/integration_test.exs

Adds dedicated publish & depublish endpoints to REST API for Podcast, Episode and AudioPublication.
Decided on `PUT` routes (`PUT /api/rest/v1/[subject]/:id/[publish|depublish]`) because that's what Github uses for [starring gists](https://developer.github.com/v3/gists/#star-a-gist) which is a somewhat similar intent.

RESTful publication actions

---

lib/radiator/podcast.ex
lib/radiator/podcast/episode.ex
lib/radiator/podcast/network.ex
lib/radiator/podcast/show.ex
priv/repo/migrations/20231124220144_create_networks.exs
priv/repo/migrations/20231127182625_create_shows.exs
priv/repo/migrations/20231127184621_create_episodes.exs
test/radiator/podcast_test.exs
test/support/fixtures/podcast_fixtures.ex

Add basic resources stations, podcasts and episodes 
related to [#497](https://github.com/podlove/radiator/issues/497)

Add base resources

---

priv/repo/seeds.exs

very basic seeds
but they also show some current missing pieces, like outlines need to be connected to episodes, there needs to be a current episode and more .. 
based on https://github.com/podlove/radiator/pull/501

Basic seeds

---

LICENSE
lib/radiator/outline/node.ex
lib/radiator/podcast.ex
lib/radiator/podcast/episode.ex
lib/radiator_web/controllers/api/outline_controller.ex
priv/repo/migrations/20231216182723_add_outline_reference_to_episode.exs
priv/repo/migrations/20231223124852_add_number_to_episodes.exs
priv/repo/seeds.exs
test/radiator/outline_test.exs
test/radiator/podcast_test.exs
test/radiator_web/controllers/api/outline_controller_test.exs
test/support/fixtures/outline_fixtures.ex

Connect nodes to episodes. This is a required argument. No node should be be dangling since they would never be shown. 
The controller expects a show_id for a node to be created. In order to connect the node the a episode we need do find a episode. In the near future this will be the one in draft mode, or even the one stored in a user preference. 
Currently it just returns the episode with the highest number. And episodes have a number now.

Connect outline nodes to episodes

---

.tool-versions
Dockerfile
assets/js/hooks/events/handler.ts
assets/js/hooks/events/listener.ts
assets/js/hooks/item.ts
assets/js/hooks/node.ts
lib/radiator/outline.ex
lib/radiator/outline/event/node_deleted_event.ex
lib/radiator/outline/event/node_inserted_event.ex
lib/radiator/outline/event/node_moved_event.ex
lib/radiator/outline/event_consumer.ex
lib/radiator_web/controllers/api/outline_controller.ex
lib/radiator_web/live/episode_live/index.ex
test/radiator/event_store_test.exs
test/radiator/outline_test.exs
test/support/fixtures/event_store_fixtures.ex

Add some EventStore Tests

---

lib/radiator/event_store.ex
lib/radiator/outline.ex
lib/radiator/outline/event/abstract_event.ex
lib/radiator/outline/event/node_content_changed_event.ex
lib/radiator/outline/event/node_deleted_event.ex
lib/radiator/outline/event/node_inserted_event.ex
lib/radiator/outline/event/node_moved_event.ex
lib/radiator/outline/event_consumer.ex
lib/radiator/outline/node.ex
lib/radiator_web/components/outline_components.ex
lib/radiator_web/live/episode_live/index.ex
test/radiator/event_store_test.exs
test/radiator/outline_test.exs
test/support/fixtures/event_store_fixtures.ex

please have a look.
question: do we need the position as an explicit value (integer)? 
if so it can be added to the node in order_nodes/3

Add virtual position

---

lib/radiator/outline.ex
lib/radiator/outline/command.ex
lib/radiator/outline/command_processor.ex
lib/radiator/outline/dispatch.ex
lib/radiator_web/live/outline_component.ex
test/radiator/outline_test.exs

I had to change the signature for `move_node` otherwise it would not be possible to differentiate between setting a value to `nil`and omitting the value. I used a keyword list since this a classic for optional parameters. Another option would be to use a map like for `insert_node`

Optional parent node for move node

---

test/radiator/outline_test.exs
test/support/fixtures/outline_fixtures.ex

use node_tree_fixture/2 to generate outline nodes described by an easy to read „template“ structure

feature: generate nodes from template

---

lib/radiator/event_store.ex
lib/radiator/outline.ex
lib/radiator/outline/command_processor.ex
lib/radiator/outline/event.ex
lib/radiator/outline/event/node_content_changed_event.ex
lib/radiator/outline/event/node_deleted_event.ex
lib/radiator/outline/event/node_inserted_event.ex
lib/radiator/outline/event/node_moved_event.ex
lib/radiator_web/components/outline_components.ex
lib/radiator_web/live/episode_live/index.ex
lib/radiator_web/live/outline_component.ex
test/radiator/event_store_test.exs
test/radiator/outline_test.exs
test/support/fixtures/event_store_fixtures.ex

so there is no need to make more db calls 
also change uuid in events to event_id
and add episode_id to NodeRepoResult
ATTENTION: some things seem broken with this change. E.g. after moving a node the content of some disappears. 
The focus gets lost after every nodechange

refactor event data: instead of sending ids provide more infos

---

lib/radiator/podcast/episode.ex
lib/radiator_web/live/episode_live/index.html.heex
priv/repo/migrations/20240916151804_add_slug_to_episodes.exs
priv/repo/seeds.exs
test/radiator/podcast_test.exs

Adding a `slug` field to Episode.
The `slug` will be generated from the `title`, every time the `title` changes the `slug` is also updated.

feature: adding slug field to episodes

---

lib/radiator/podcast.ex
lib/radiator/podcast/episode.ex
lib/radiator_web/live/episode_live/index.ex
priv/repo/migrations/20240918192918_add_is_deleted_to_episodes.exs
test/radiator/podcast_test.exs

Marking episodes as `is_deleted = true` and setting `deleted_at = now`. 
`list_available_episodes` gives all episodes that are NOT marked as deleted. 
`list_all_episodes` gives all episodes including the once that are marked as deleted.

feature: Soft deleting episode

---

lib/radiator/application.ex
lib/radiator/job.ex
lib/radiator/job_supervisor.ex
lib/radiator/outline/node.ex
lib/radiator/outline/node_change_listener.ex
lib/radiator/resources.ex
lib/radiator/resources/url_worker.ex
test/radiator/resources/url_worker_test.exs
test/radiator/resources_test.exs
test/support/fixtures/resources_fixtures.ex

Prepares detecting and processing of URLs in node texts. 
Provides a very basic mechanism for running async jobs 
Whats missing: 
- scrape/analyze URLs
- show URLs in UI

Start with job workers

---

lib/radiator/accounts.ex
lib/radiator/accounts/raindrop_client.ex
lib/radiator/accounts/user.ex
lib/radiator/accounts/web_service.ex
lib/radiator_web/controllers/api/raindrop_controller.ex
lib/radiator_web/live/admin_live/index.ex
lib/radiator_web/live/admin_live/index.html.heex
priv/repo/migrations/20241105184254_create_web_services.exs
priv/repo/migrations/20241106201557_remove_rainbow_tokens_from_user.exs
test/radiator/accounts/raindrop_client_test.exs
test/radiator/accounts_test.exs
test/radiator_web/controllers/api/raindrop_controller_test.exs
test/support/fixtures/accounts_fixtures.ex

Introduces a new schema `web_services` which is supposed to store data for all kinds of possible external services. First implementation is for `Raindrop.io`. Hence the branchname the embedded data for the service it is not yet polymorphic. 
In the Admin Show settings a show can now be associated with a raindrop collection. 
Still missing: URL synchonization with an inbox folder.

 add userservices model

---

lib/radiator/outline/node.ex
priv/repo/migrations/20241222120855_remove_type_from_nodes.exs

we now are using node containers for these purposes. the attribute is not used anymore

remove _type attribute from nodes again
