podlove/radiator

- config/dev.exs
> chore(webpack): enabled colorized output

- lib/radiator/auth/register.ex
- lib/radiator/auth/user.ex
- priv/repo/migrations/20190319092448_add_users_table.exs
- test/radiator_web/graphql/schema/mutation/users_test.exs
Closes #40 when accepted and reviewed.
> feat(auth,user): make Register.get_user_by_credentials/2 case insensitive

- .drone.yml
- README.md
- config/test.exs
- entrypoint.sh
Does not solve issue #96 but it's an improvement.
> chore: use separate minio bucket for testing

- lib/radiator/directory/episode_query.ex
- lib/radiator_web/controllers/admin/podcast_controller.ex
- lib/radiator_web/graphql/admin/schema.ex
- lib/radiator_web/graphql/admin/schema/directory_types.ex
- lib/radiator_web/graphql/public/schema.ex
- lib/radiator_web/graphql/public/schema/directory_types.ex
- test/radiator_web/graphql/admin/schema/query/episodes_test.exs
- test/radiator_web/graphql/public/schema/query/episodes_test.exs
> fix: default episode order is descending by published_at

- lib/radiator/directory.ex
- lib/radiator/directory/editor.ex
- lib/radiator/directory/episode_query.ex
> doc: add documentation for querying episodes

- lib/radiator_web/templates/admin/podcast/index.html.eex
- lib/radiator_web/views/admin/podcast_view.ex
> fix(podcast): shorten podcast description

- lib/radiator/audio_meta/audio_meta.ex
> feat: remove images of deleted chapters

- lib/radiator/directory.ex
- lib/radiator/directory/audio_query.ex
- lib/radiator_web/controllers/player_controller.ex
- lib/radiator_web/router.ex
- lib/radiator_web/templates/admin/episode/show.html.eex
- add config URLs for audios and episodes
- display web player on episode page instead of HTML5 audio element
fixes #80
> feat: add support for Podlove Web Player

- lib/radiator/auth/register.ex
- lib/radiator/auth/user.ex
- lib/radiator_web/controllers/admin/usersettings_controller.ex
- lib/radiator_web/router.ex
- lib/radiator_web/templates/admin/user_settings/usersettings.html.eex
- lib/radiator_web/templates/login/signup.html.eex
- lib/radiator_web/templates/page/nav.html.eex
- lib/radiator_web/views/admin/usersettings_view.ex
Implement the first part of #27.
> Password Change

- lib/radiator_web/templates/admin/episode/show.html.eex
Fixes https://github.com/podlove/radiator/issues/122
> Fix showing of episode when audio is not yet set

- lib/radiator/directory/importer.ex
- lib/radiator_web/graphql/feed_info/resolvers/metalove.ex
- lib/radiator_web/graphql/feed_info/types.ex
- lib/radiator_web/graphql/schema.ex
This is the proposed addition to the GraphQL Schema:
```GraphQL
type RootQueryType {
"""Get podcast feed info for an url"""
feedInfo(url: String!): FeedInfo
"""Get the content of a feed url"""
podcastFeed(url: String!): PodcastFeed
}
"""Info about podcast feeds found at an url"""
type FeedInfo {
feeds: [PodcastFeed]
image: String
link: String
subtitle: String
suggestedShortId: String
title: String
}
"""A Podcast feed"""
type PodcastFeed {
author: String
description: String
episodeCount: Int!
episodes: [PodcastFeedEpisode]
feedUrl: String
image: String
link: String
subtitle: String
summary: String
title: String
enclosure_type: String
waitingForPages: Boolean!
}
"""A podcast feed episode"""
type PodcastFeedEpisode {
contentEncoded: String
description: String
duration: String
enclosureType: …
```
> feat(api): provide api for metalove information about feeds to facilitate the import feature

- guides/data_and_structure.md
- guides/graphql_api.md
- guides/rest_api.md
- lib/radiator/contribution/audio_contribution.ex
- lib/radiator/contribution/podcast_contribution.ex
- lib/radiator/contribution/role.ex
- lib/radiator/directory/editor.ex
- lib/radiator/directory/editor/editor.ex
- lib/radiator_web/controllers/api/contribution_controller.ex
- lib/radiator_web/graphql/admin/resolvers/editor.ex
- lib/radiator_web/graphql/admin/types.ex
- lib/radiator_web/graphql/common/types.ex
- lib/radiator_web/graphql/public/types.ex
- lib/radiator_web/graphql/schema.ex
- lib/radiator_web/router.ex
- lib/radiator_web/templates/admin/episode/show.html.eex
- lib/radiator_web/views/api/contribution_view.ex
- lib/radiator_web/views/helpers/content_helpers.ex
- priv/repo/migrations/1150_create_roles.exs
- priv/repo/migrations/1200_create_contributions.exs
- priv/repo/seeds.exs
documentation in `rest_api.md` and `graphql_api.md`
fixes #139 
needs ecto.reset
> feature(api, content): contribution REST and GraphQL API

- .drone.yml
- lib/radiator/audio_meta/audio_meta.ex
- lib/radiator/audio_meta/dataloader_provider.ex
- lib/radiator/directory.ex
- lib/radiator/directory/dataloader_provider.ex
- lib/radiator_web/graphql/admin/resolvers/editor.ex
- lib/radiator_web/graphql/admin/types.ex
- lib/radiator_web/graphql/common/types.ex
- lib/radiator_web/graphql/public/types.ex
- lib/radiator_web/graphql/schema.ex
- fixes #147
- uses dataloader more consistently instead of relying on preloaded data
> GraphQL improvements

- .drone.yml
- README.md
- entrypoint.sh
- lib/radiator/directory.ex
- lib/radiator/directory/audio_publication.ex
- lib/radiator/directory/episode.ex
- lib/radiator/directory/title_slug.ex
- lib/radiator/media/audio_file.ex
- lib/radiator/tracking.ex
- lib/radiator/tracking/download.ex
- lib/radiator_web/controllers/player_controller.ex
- lib/radiator_web/controllers/tracking_controller.ex
- lib/radiator_web/router.ex
- priv/repo/migrations/0350_create_audio_publications.exs
- priv/repo/migrations/1000_create_downloads.exs
- test/radiator/directory/directory_test.exs
- test/radiator/directory/title_slug_test.exs
- test/radiator/tracking/tracking_test.exs
- test/support/factory.ex
- updated tracking URLs and made them work again
- added AudioPublication to tracking
- add slug logic to AudioPublication
- update `AudioFile.public_url` (tracking URL) generation
closes #127
> Issue/127 Fix Tracking

- lib/radiator/contribution/person.ex
- priv/repo/migrations/1100_create_people.exs
- test/radiator/contribution/people_test.exs
also adds a simple test for people
needs ecto.reset
fixes #202
> fix (data): require `display_name` for a person

- lib/radiator/tracking.ex
- lib/radiator/tracking/download.ex
- lib/radiator_web/controllers/tracking_controller.ex
- priv/repo/migrations/1000_create_downloads.exs
- test/radiator/tracking/tracking_test.exs
> add: track download http referer

- guides/data_and_structure.md
- guides/graphql_api.md
- lib/radiator/directory.ex
- lib/radiator/directory/episode_query.ex
- lib/radiator/directory/podcast.ex
- lib/radiator_web/controllers/public/feed_controller.ex
- lib/radiator_web/graphql/admin/types.ex
- lib/radiator_web/graphql/common/types.ex
- lib/radiator_web/graphql/public/resolvers/directory.ex
- lib/radiator_web/graphql/public/types.ex
also updated the `graphql_api.md` file with the current state of affairs
fixes #219
> feature(api): add `publicPage` to podcast and episode and add  `publishedFeeds` to `Podcast` in GraphQL API

- lib/radiator/directory.ex
> fix(public): ensure full publication for public episode pages

- guides/rest_api.md
- lib/radiator/directory.ex
- lib/radiator/directory/episode_query.ex
- lib/radiator/directory/podcast_query.ex
- lib/radiator_web/graphql/admin/types.ex
- remove unused Radiator.Directory.get_episode_by_short_id/1
- rename find_by_short_id functions to filter_by_short_id, matching their implementation
- improve REST/GQL docs
> refactor: clarify short_id is not unique

- config/dev.exs
- config/prod.exs
- config/test.exs
- lib/radiator/cldr.ex
- lib/radiator_web/router.ex
- lib/radiator_web/views/api/episode_view.ex
- lib/radiator_web/views/helpers/format_helpers.ex
- mix.exs
- test/radiator/directory/directory_test.exs
- test/radiator/directory/editor/permission_test.exs
- test/radiator/directory/episode_guid_test.exs
- test/radiator/directory/title_slug_test.exs
- test/radiator/feed/builder_test.exs
- test/radiator/tracking/tracking_test.exs
- test/radiator_web/controllers/api/episode_controller_test.exs
- test/radiator_web/controllers/api/integration_test.exs
- test/radiator_web/controllers/api/podcast_controller_test.exs
- test/radiator_web/controllers/feed_controller_test.exs
- test/radiator_web/controllers/public/episode_controller_test.exs
- test/radiator_web/graphql/admin/schema/query/episodes_test.exs
- test/radiator_web/graphql/admin/schema/query/podcasts_test.exs
- test/radiator_web/graphql/public/schema/query/episodes_test.exs
- test/radiator_web/graphql/public/schema/query/networks_test.exs
- test/radiator_web/graphql/public/schema/query/podcasts_test.exs
- test/support/factory.ex
- improve Phoenix startup speed in test & dev
- improve compile time (removes barely used cldr library)
- refactor test factories
- add tests
> Regression tests & Performance

- lib/radiator/outline.ex
- lib/radiator/outline/node.ex
- lib/radiator_web/live/outline_live/index.ex
- lib/radiator_web/live/outline_live/index.html.heex
- priv/repo/migrations/20231120103619_create_outline_nodes.exs
- test/radiator/outline_test.exs
- test/radiator_web/live/outline_live_test.exs
- test/support/fixtures/outline_fixtures.ex
closes https://github.com/podlove/radiator/issues/493
> add: inbox & outline context

- .github/workflows/cd.yml
- .tool-versions
@see https://www.tzeyiing.com/posts/2024/02/13/setup-beam-with-asdf-tool-version link to version managers: https://mise.jdx.dev or https://asdf-vm.com
> add `asdf` or `mise` support

- assets/js/hooks/index.ts
- assets/js/hooks/item.ts
- assets/tailwind.config.js
- lib/radiator_web/live/outline_component.html.heex
- each user has it's own <span> tag
- each user name is displayed in one of 12 colors * 3 intensities = 36 color variations
- color selection is based on first char and user name length
> feature: display all editing users in different colors

- lib/radiator/outline.ex
- lib/radiator/outline/command.ex
- lib/radiator/outline/command/outdent_node_command.ex
- lib/radiator/outline/command_processor.ex
- lib/radiator/outline/dispatch.ex
- lib/radiator/outline/event/node_moved_event.ex
- lib/radiator_web/live/outline_component.ex
- test/radiator/outline_test.exs
- test/support/data_case.ex
implements outdent working like in outliner
fixes also a new bug in insert node when parent id is not given
> Outdent nodes

- .tool-versions
- Dockerfile
> bump elixir version to 1.18.1
